version: '3.4'

services:
  nginx:
    container_name: web
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: app
    image: youtubeenglishdrf
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
      ]
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./:/app:cached
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
