version: '3.4'

services:
  nginx:
    container_name: web
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: app
    image: ghcr.io/stada526/youtube-english-drf:latest
    command: rye run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
